markdown: rdiscount
highlighter: true
plugins: ./_plugins
paginate: 15
paginate_path: "index/page:num"

safe: false

#站点基础配置
title: 十又十分之一
subTitle: 飞翔之猴
description: 
url: http://www.bytetown.net
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /contact.html
    icon: icon-envelope-alt
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: 十又十分之一
